# Generated by Django 4.2 on 2024-08-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rating',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
