# Generated by Django 4.2 on 2024-08-10 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_student_group_id_student_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='group_id',
            new_name='group',
        ),
    ]
