# Generated by Django 5.1 on 2024-08-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='pictures/default.jpg', null=True, upload_to='pictures/'),
        ),
    ]
