# Generated by Django 5.1 on 2024-09-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_opened',
            field=models.BooleanField(default=False),
        ),
    ]
