import copy
from urllib.parse import urlencode


class QueryParamsInjectorMiddleware:
    """
        Middleware to inject modified query parameters into the request.

        class QueryParamsInjectorMiddleware:

            def __init__(self, get_response):
                Initializes the middleware with the given response handler.

                Parameters:
                get_response (callable): The next middleware in the stack or the final view handler.

            def __call__(self, request):
                Processes the incoming request, modifies query parameters, and passes the request on.

                Parameters:
                request (HttpRequest): The HTTP request object.

                Returns:
                HttpResponse: The HTTP response object generated by the next middleware or view.
    """

    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):

        query_params = copy.deepcopy(request.GET)
        if 'page' in query_params:
            del query_params['page']

        request.query_params = urlencode(query_params)

        response = self.get_response(request)

        return response
