# Generated by Django 4.2 on 2024-08-05 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='birthdate',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
