# Generated by Django 4.2 on 2024-08-05 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='birthdate',
            field=models.DateTimeField(default=datetime.date.today, null=True),
        ),
    ]
