# Generated by Django 4.2 on 2024-08-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_alter_teacher_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=64, null=True),
        ),
    ]
