# Generated by Django 4.2 on 2024-08-10 17:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_teacher_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
